---
title: "New GP"
output: html_notebook
---


```{r}
install.packages("tidyverse", "rstan")
library(rstan, tidyverse)
n <- 200
m <- 10
x1 <- rnorm(n, mean = 0, sd = 5)
x2 <- x1 + 3
x3 <- 2*x2+x1+ rnorm(n, mean = 0, sd = .1)
y<- x3+.8*x1+rnorm(n, mean = 0, sd = .5)
data <- data.frame(x1, x2, x3)
x1s <- rnorm(m, mean = 0, sd = 5)
x2s <- x1s + 3
x3s <- 2*x2s+x1s +  rnorm(m, mean = 0, sd = .1)
ys <- x3s+.8*x1s+rnorm(m, mean = 0, sd = .5)
data_pred <- data.frame(x1s, x2s, x3s)
print(x1)
print(ys)
```


```{r}
simu_data <- list(N = n,D =  3, M = m, x = data,y = y, x_pred = data_pred, ell= c(2, .5, 1),  sf=1,  sn=1e-5)
```


```{r}
ell = c(1, 2, 1)
sandbox_data <- list(N = n, ell = ell, D=3, x = data)
#sweep(as.matrix(data), 2, ell, "/")
```

```{r}
writeLines(readLines("sandbox.stan"))
simu_fit <- stan(file='sandbox.stan', data=sandbox_data,
                 warmup=0, iter=4000, chains=1, seed=494838,
                 algorithm="Fixed_param", refresh=1000)
```

```{r}
writeLines(readLines("Algorithm_1.stan"))
GP_fit <- stan(file='Algorithm_1.stan', data=simu_data,
                 warmup=0, iter=4000, chains=1, seed=494838,
                 algorithm="Fixed_param", refresh=100)
```

```{r}
sample = extract(GP_fit, pars = c('y_pred', 'eta'))
#print(sample$y_pred[3214,])
print(sample$y_pred[199,])
print(ys)
```

```{r}
train <- data.frame(x1, y, TRUE)[order(x1),]
test <- data.frame(x1s, ys, FALSE)[order(x1s),]
train_dat <- data.frame("x" = train[,1], "y" = train[,2], "is_train" = train[,3])
test_dat <- data.frame("x" = test[,1], "y" = test[,2], "is_train" = test[,3])
input_data <- rbind(test_dat, train_dat)
print(train_dat)
input_data <- input_data[order(input_data$x),]
print(input_data[,1])
#Approximate solution for quad-exp given for Matern(7/2) kernel
```

```{r}
alg2_data <- list(N = n+m, x_raw = input_data[,1], y_raw = input_data[,2], train = input_data[,3], ell = 10, sf=1,  sn=1e-5)
writeLines(readLines("Algorithm_2.stan"))
GP_fit <- stan(file='Algorithm_2.stan', data=alg2_data,
                 warmup=0, iter=4000, chains=1, seed=494838,
                 algorithm="Fixed_param", refresh=100)
```



